/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tariqmnasim_jnitest_CppLibJNITest */

#ifndef _Included_com_tariqmnasim_jnitest_CppLibJNITest
#define _Included_com_tariqmnasim_jnitest_CppLibJNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tariqmnasim_jnitest_CppLibJNITest
 * Method:    showMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tariqmnasim_jnitest_CppLibJNITest_showMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tariqmnasim_jnitest_CppLibJNITest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tariqmnasim_jnitest_CppLibJNITest_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tariqmnasim_jnitest_CppLibJNITest
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tariqmnasim_jnitest_CppLibJNITest_multiply
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
