/* DO NOT EDIT THIS FILE - it is machine generated */
#include "CppLib.h"
#include <jni.h>
/* Header for class com_tariqmnasim_jnitest_CppLibJNITest */

#ifndef _Included_com_tariqmnasim_jnitest_CppLibJNITest
#define _Included_com_tariqmnasim_jnitest_CppLibJNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tariqmnasim_jnitest_CppLibJNITest
 * Method:    showMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tariqmnasim_jnitest_CppLibJNITest_showMessage
  (JNIEnv *jniEnv, jobject jObject, jstring msg) {
	const char *str = jniEnv->GetStringUTFChars(msg, 0);
	showMessage(str);
}

/*
 * Class:     com_tariqmnasim_jnitest_CppLibJNITest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tariqmnasim_jnitest_CppLibJNITest_add
  (JNIEnv *jniEnv, jobject jObject, jint a, jint b) {
	return add(a, b);
}

/*
 * Class:     com_tariqmnasim_jnitest_CppLibJNITest
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tariqmnasim_jnitest_CppLibJNITest_multiply
  (JNIEnv *jniEnv, jobject jObject, jint a, jint b) {
	return multiply(a, b);
}

#ifdef __cplusplus
}
#endif
#endif
